(()=>{const style=document.createElement('style');style.textContent='.float{display:none!important}.floating-actions{display:none;position:fixed;left:12px;right:12px;bottom:12px;z-index:9999;grid-template-columns:1fr 1fr;gap:10px;padding:8px;border-radius:20px;background:rgba(18,14,12,.88);border:1px solid rgba(255,255,255,.13);backdrop-filter:blur(16px);box-shadow:0 18px 55px rgba(0,0,0,.45)}.floating-btn{min-height:58px;display:flex;align-items:center;justify-content:center;border-radius:14px;font-weight:900;font-family:Cairo,sans-serif;transition:transform .2s ease,filter .2s ease}.floating-btn:active{transform:scale(.97)}.floating-wa{background:linear-gradient(135deg,#34d27b,#16a95a);color:#07150d}.floating-call{background:linear-gradient(135deg,#f0d28c,#bd9345);color:#17110b}.floating-wa:before{content:"◉";margin-left:8px;font-size:1.05rem}.floating-call:before{content:"☎";margin-left:8px;font-size:1.05rem}.shot.image-ready{animation:imageIn .45s ease both}.shot.image-error:after{content:"";position:absolute;inset:0;background:linear-gradient(135deg,rgba(225,193,124,.11),rgba(255,255,255,.02))}@keyframes imageIn{from{opacity:.25;transform:scale(.985)}to{opacity:1;transform:none}}@media(max-width:980px){.floating-actions{display:grid}body{padding-bottom:92px}}';document.head.appendChild(style)})();

(async()=>{try{const files=['assets/sprite-00.txt','assets/sprite-01.txt','assets/sprite-02.txt','assets/sprite-03.txt','assets/sprite-04.txt','assets/sprite-05.txt','assets/sprite-06.txt','assets/sprite-07.txt'];const parts=await Promise.all(files.map(async f=>{const r=await fetch(f,{cache:'no-store'});if(!r.ok)throw new Error(f+' '+r.status);return (await r.text()).trim()}));const b64=parts.join('');const binary=atob(b64);const bytes=new Uint8Array(binary.length);for(let i=0;i<binary.length;i++)bytes[i]=binary.charCodeAt(i);const imageUrl=URL.createObjectURL(new Blob([bytes],{type:'image/webp'}));document.querySelectorAll('.shot').forEach(el=>{el.style.backgroundImage=`url("${imageUrl}")`;el.classList.add('image-ready')});}catch(e){console.error('sprite load failed',e);document.querySelectorAll('.shot').forEach(el=>el.classList.add('image-error'))}})();

window.dataLayer=window.dataLayer||[];
const ENDPOINT='https://script.google.com/macros/s/AKfycbzuBfuMOFQC-0_WU8r62PY5l3MD4vDPfxN36w1WFe5uGD8yEtiRS086moiU0zbhNGF9/exec';
const keys=['gclid','gbraid','wbraid','utm_source','utm_medium','utm_campaign','utm_term','utm_content'];
const params=new URLSearchParams(location.search);
keys.forEach(k=>{const v=params.get(k);if(v)try{localStorage.setItem(k,v)}catch(e){}});

document.querySelectorAll('.js-call').forEach(a=>a.addEventListener('click',()=>dataLayer.push({event:'phone_click',phone_number:'+966567031077'})));
document.querySelectorAll('.js-wa').forEach(a=>a.addEventListener('click',()=>dataLayer.push({event:'whatsapp_click'})));

const oldFloat=document.querySelector('.float');
if(oldFloat){const floating=document.createElement('div');floating.className='floating-actions';floating.innerHTML='<a class="floating-btn floating-wa js-wa" href="https://wa.me/966567031077?text=%D9%85%D8%B1%D8%AD%D8%A8%D8%A7%D8%8C%20%D8%A3%D8%B1%D9%8A%D8%AF%20%D9%85%D9%86%D8%A7%D9%82%D8%B4%D8%A9%20%D8%AE%D8%AF%D9%85%D8%A7%D8%AA%20%D8%A5%D9%8A%D8%B3%D8%AA%20%D8%AA%D9%88%D9%8A%D8%B3%D8%AA" target="_blank" rel="noopener"><span>واتساب</span></a><a class="floating-btn floating-call js-call" href="tel:+966567031077"><span>اتصال</span></a>';oldFloat.replaceWith(floating);floating.querySelector('.js-call').addEventListener('click',()=>dataLayer.push({event:'phone_click',phone_number:'+966567031077'}));floating.querySelector('.js-wa').addEventListener('click',()=>dataLayer.push({event:'whatsapp_click'}));}

const form=document.getElementById('leadForm');
if(form)form.addEventListener('submit',async e=>{e.preventDefault();if(!e.target.checkValidity()){e.target.reportValidity();return}const btn=e.target.querySelector('button');const s=document.getElementById('status');btn.disabled=true;btn.textContent='جارٍ الإرسال';s.className='status';const d=Object.fromEntries(new FormData(e.target));keys.forEach(k=>{try{d[k]=localStorage.getItem(k)||''}catch(x){d[k]=''}});d.landing_page=location.href;d.referrer=document.referrer;d.event_id='lead_'+Date.now()+'_'+Math.random().toString(36).slice(2);d.user_agent=navigator.userAgent;d.language=navigator.language;try{await fetch(ENDPOINT,{method:'POST',mode:'no-cors',headers:{'Content-Type':'text/plain;charset=utf-8'},body:JSON.stringify(d)});dataLayer.push({event:'lead_form_submit',lead_service:d.service,event_id:d.event_id});s.textContent='تم استلام طلبك بنجاح، وسيتواصل معك فريق إيست تويست.';s.className='status show success';e.target.reset()}catch(err){s.textContent='تعذر الإرسال حاليًا. تواصل معنا عبر الاتصال أو واتساب.';s.className='status show error'}finally{btn.disabled=false;btn.textContent='إرسال طلب التواصل'}});